# Generated by Django 4.1.3 on 2023-04-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_color_remove_profile_home_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
    ]
